# Generated by Django 3.2.6 on 2022-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя сайта клиента')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проблемы клиента')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовый ящик для связи с клиентом')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон для связи с клиентом')),
                ('inform', models.TextField(blank=True, null=True, verbose_name='Откуда клиент узнал о услугах')),
            ],
            options={
                'verbose_name': 'Сообщения с главной формы сайта',
                'verbose_name_plural': 'Сообщение с главной формы сайта',
            },
        ),
    ]
